### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Rufino07#1]
[TypeScript.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Rufino07/files/15224605/TypeScript.pdf)

**Comment by josealfredo79** [comment]
calificacion..???

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Se necesita la calificaciòn 19
